### ISSUE TITLE
Cannot build a project after cloning the repo

### ISSUE THREAD

**Issue by Streebor** [marc-maguire/Juke#26]
<img width="1142" alt="screen shot 2017-07-13 at 4 48 42 pm" src="https://user-images.githubusercontent.com/6864357/28187007-277d1c4e-67eb-11e7-8e8f-b1f1072a4303.png">

I tried cloning both master and develop branches

**Comment by marc-maguire** [comment]
I'll double check in the morning if it has to do with us keeping an API key private.

**Comment by marc-maguire** [comment]
Confirmed - We kept the Spotify client ID off GitHub to be safe. The project will not work without it. Closing issue, will research whether or not it's safe to post it.
